### ISSUE TITLE
Sierra Leone Error

### ISSUE THREAD

**Issue by kiranpande** [dcgull/WPDx-Toolset#4]
The tools work for all countries except Sierra Leone. Service Overview works for Sierra Leone, but the tools that require inputting an administrative zone results in an error (attached). 

![sl repair](https://user-images.githubusercontent.com/41437977/42947451-57c26f2a-8b3b-11e8-9879-27645a3117fb.PNG)

![sl update rural](https://user-images.githubusercontent.com/41437977/42947452-57cfba90-8b3b-11e8-8a49-b90b67a92771.PNG)

**Comment by slibby** [comment]
Can you share the Inputs that you used during these failed attempts - or expand the "Inputs" section of the message you posted?

**Comment by kiranpande** [comment]
The below is one example. I've tried all the administrative zones and still get the same error. 
![capture2](https://user-images.githubusercontent.com/41437977/43322117-b6b96fb0-917b-11e8-8b52-2c9f1a43f470.PNG)

**Comment by slibby** [comment]
@dcgull any ideas here? I think `Southern` may not be a valid administrative area.

**Comment by slibby** [comment]
This is because Southern exists in both Zimbabwe and Sierra Leone so there was a conflict. Do you want to change the tool to have a Country selector as the first parameter? @kiranpande

**Comment by slibby** [comment]
add the highlighted text in wpdx.py:

![image](https://user-images.githubusercontent.com/1691225/43862608-62f668ec-9b17-11e8-9456-5a7cb1a8f866.png)

**Comment by kiranpande** [comment]
I think all of the districts (Northern, Eastern, Western, Southern) all get the same error, probably because they exist in other countries too? 

Would adding a country selector help if its already pulling from the world pop data for Sierra Leone?

**Comment by slibby** [comment]
Yes because it is using one global ADM2 boundary layer to find the polygon to analyze. So we need to add either a country selector or a variable that allows the tool to only be used for one country at a time. See above to get it working and let's see if that gets you going for your demonstration.

**Comment by kiranpande** [comment]
Ok that makes sense, thank you! Where can I find wpdx.py?

**Comment by slibby** [comment]
@kiranpande it should be in the same folder as the .pyt toolbox file.

**Comment by kiranpande** [comment]
Thanks, Sam! 

So, I right clicked on the toolset in GIS and added the code in the right place (I think... based on the other text surrounding it), saved it, refreshed, and tried to run the tools but none of the tools had a country selector. 

Am I missing something or did I make the edit in the wrong place? Sorry if this is super simple and I'm just missing it... I'm not too familiar with this side of things!

**Comment by slibby** [comment]
@kiranpande that edit is just to fix it so that `Southern` will work - it basically hard-codes Sierra Leone as the country. No selector yet, that will require more code + time.

**Comment by kiranpande** [comment]
Ok that makes sense! Thanks for the clarification. 

I tried to run the unserved pop and update rural pop and got the errors below. Do you think I made an error adding in the code? 

![ruralpopsl](https://user-images.githubusercontent.com/41437977/43864214-19b6f1b8-9b2d-11e8-82dc-24593df4fe91.PNG)
![unservedpopsl](https://user-images.githubusercontent.com/41437977/43864215-19c39ea4-9b2d-11e8-8bba-126a19e758c4.PNG)

**Comment by slibby** [comment]
Not an issue, just an issue with my "fix" - this is the kind of thing that we need time to improve. Stand by.

**Comment by dcgull** [comment]
Hey, sorry I don't have time to help with this right now, but it looks like you guys are on the right track. I should have realized district names would not be unique!

**Comment by kiranpande** [comment]
Ok thank you both so much!

**Comment by slibby** [comment]
@kiranpande change the section in wpdx.py for setEnvironment to this block of text:

```
def setEnvironment(zone, query_type):
    """Limits the processing extent to the given administrative zone"""
    arcpy.env.overwriteOutput = True
    adm_zones = join(dirname(__file__), "Data", "ToolData.gdb", "Admin")
    if zone in ["Northern", "Southern", "Eastern", "Western"]:
        mask = arcpy.FeatureClassToFeatureClass_conversion(adm_zones, "in_memory", "mask",
                                                            "{0}='{1}' and CC = 'SL'".format(query_type, zone))
    else:
        mask = arcpy.FeatureClassToFeatureClass_conversion(adm_zones, "in_memory", "mask",
                                                            "{0}='{1}'".format(query_type, zone))
    if mask.maxSeverity==1:
        arcpy.AddError("ERROR: Database error in {}. Please alert system administrator".format(zone))
        sys.exit(1)
    else:
        extent = arcpy.Describe(mask).extent
        arcpy.env.extent = extent
        #arcpy.env.mask = mask
        return mask
```

**Comment by kiranpande** [comment]
Thanks, Sam! I just got home, but I'll test this out first thing. Should I remove the text i added earlier?

**Comment by kiranpande** [comment]
Hi Sam, 

Sorry for the delay. I replaced the old text and got the error below. My methods have just been to open GIS, right click on the toolset, click edit (opens the text in notepad) and edit from there. Have the errors been caused on my end? Let me know if there is a better way I should be updating!

![sl error 8 9](https://user-images.githubusercontent.com/41437977/43919364-b4b4b8ba-9be3-11e8-995f-b0f2a0fbb715.PNG)

**Comment by slibby** [comment]
These are some of the fixes I am trying to make to the tool.

Find line 684 in the .pyt file and add `wpdx.` to the front of the `queryWPDx` variable. You may find other places where you have the same issue. 

It would be easiest if I get logged in via the VPN, and we'll get everything working for your demos if we can.

**Comment by kiranpande** [comment]
Ok thanks! I sent you the VPN information yesterday - let me know if you have trouble accessing it or navigating the folder!

**Comment by slibby** [comment]
@kiranpande I believe it is working properly now - can you please verify? I tried a number of different workflows in SL and they all seemed to work well.

**Comment by kiranpande** [comment]
Thank you so much, Sam! We really appreciate you taking the time to help sort this out. 

I downloaded the toolset again and ran the tools but got this new error. If they're working for you it is probably an issue on our side. I'm accessing the server from my laptop right now but will check it again tomorrow morning when I have access to a better computer in the office. 

![background error](https://user-images.githubusercontent.com/41437977/43929658-e92abfca-9c03-11e8-9052-0d081eb7a13a.PNG)

**Comment by slibby** [comment]
@kiranpande unfortunately downloading the tools again overwrote the fixes that I applied to your system - do you still have the 8.8.18 folder? That is where I had applied changes.

**Comment by kiranpande** [comment]
I tried the toolset in the 8.8.18 folder initially but got the same error. So I downloaded it again to try fresh. I apologize if I did something along the way to mess up the toolset... Let me know if there is something I can do on my end to fix it - I don't want to make you duplicate your efforts!

**Comment by slibby** [comment]
@kiranpande It still working OK for me, can you contact me on skype at `slibbs` and we'll try to get it going for you.
