### ISSUE TITLE
Continental Data setup

### ISSUE THREAD

**Issue by slibby** [dcgull/WPDx-Toolset#6]
@kiranpande Can you share some details about how the data is structured on your server? I understand you have the global WorldPop dataset and I'm interested in where/how that's stored and what your Paths.txt file looks like.

**Comment by slibby** [comment]
Also, can you share the external URL or IP address of your Enterprise environment?

**Comment by kiranpande** [comment]
I downloaded all the files from GitHub and saved them on the local drive of our computer (where we save all our GIS work). When I use the tools for each country I copy and paste the path/url of the file into the paths document before running the tools.

**Comment by kiranpande** [comment]
I'll send you an email with the VPN instructions and the IP of our GIS server. That will give you access to the computer with our ArcGIS Desktop account, let me know if you're talking about something else. Thank you so much for all your help!

**Comment by slibby** [comment]
@kiranpande that will help. Thanks.

**Comment by dcgull** [comment]
Hey, so if you put all the population rasters into a mosaic dataset, you can just point the paths.txt towards that mosaic
