### ISSUE TITLE
Extent of results

### ISSUE THREAD

**Issue by slibby** [dcgull/WPDx-Toolset#7]
@dcgull it appears to me that tools like Find New Locations use the extent of the raster and do not clip to the extent of the Admin Areas - 

I.e. this was a run for "Northern" in Sierra Leone:

![image](https://user-images.githubusercontent.com/1691225/43926478-a3e2a412-9be7-11e8-869f-bf41862c64ce.png)

and the points appear outside of the actual Northern area - but within the x/y extent of the Northern area. 

Is this by design or do we have something configured wrong?

**Comment by dcgull** [comment]
Right now it clips to the bounding box of the admin area, but not its actual shape. This was something I meant to fix.
